version: 1

# This controls how dependabot creates PRs for dependencies:
# See: https://dependabot.com/docs/config-file/

update_configs:

  - package_manager: python
    directory: /docker
    update_schedule: live
  - package_manager: docker
    directory: /docker
    update_schedule: daily 
    automerged_updates:
    - match:
        dependency_name: demisto/*
        update_type: all
